---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(dewey)
library(data.table)
library(tidyverse)
library(sparklyr)

Sys.setenv(JAVA_HOME = "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home")
```

```{r}
sc <- spark_connect(master = "local")

# if(file.exists("source")) unlink("source", TRUE)
# if(file.exists("source-out")) unlink("source-out", TRUE)
# 
# stream_generate_test(iterations = 1)
# list.files("source")
# 
# read_folder <- stream_read_csv(sc, "source")

# spark_disconnect(sc)
```

```{r}
# load the wait time files
files <-
  data.table("filePath" = grep("*\\.csv", list.files("data/"), value = TRUE)) %>%
  .[, "rideName" :=  sub("(\\_old)?\\.csv", "", filePath)] %>%
  .[, rideName := ifelse(rideName == "7_dwarfs_train", "dwarfs_train", rideName)]

round_time = function(x, precision, method = round) {
  if ("POSIXct" %in% class(x) == FALSE)
    stop("x must be POSIXct")
  
  tz = attributes(x)$tzone
  secs_rounded = method(as.numeric(x) / precision) * precision
  as.POSIXct(secs_rounded, tz = tz, origin = "1970-01-01")
}

longerData <- function(x) {
  rbindlist(
    list(x %>% 
           .[, .(RIDENAME, date, datetime, SACTMIN)] %>% 
           .[, `:=`(TYPE = "SACTMIN", WAITTIME = SACTMIN, SACTMIN = NULL)],
         x %>% 
           .[, .(RIDENAME, date, datetime, SPOSTMIN)] %>% 
           .[, `:=`(TYPE = "SPOSTMIN", WAITTIME = SPOSTMIN, SPOSTMIN = NULL)])
    )
}

dt <- unique(rbindlist(apply(files, 1, function(x) { 
    fread(paste0("data/", x["filePath"])) %>%
    .[!is.na(SPOSTMIN) & SPOSTMIN >= 0 | !is.na(SACTMIN) & SACTMIN >= 0] %>%
    .[, RIDENAME := x["rideName"]]
  }), use.names = TRUE)) %>%
  longerData(.) %>%
  .[, `:=`(DATE = as.ordered(format(as.Date(date, format = "%m/%d/%Y"), 
                                    format = "%m-%d")),
           date = NULL,
           DATETIME = round_time(datetime, 60*5, floor),
           datetime = NULL)] %>%
  .[, `:=`(MONTH = month(DATETIME),
           DAY = mday(DATETIME),
           TIME = as.ITime(DATETIME),
           DATETIME = NULL)] %>%
  .[, WAITTIMEmean := mean(log(WAITTIME), na.rm = TRUE),
    by = .(RIDENAME, TYPE, DATE, MONTH, DAY, TIME)] %>%
  .[, WAITTIME := NULL] %>%
  .[order(RIDENAME, DATE, TYPE, TIME)] %>%
  unique() %>%
  dcast(., DATE + MONTH + DAY + TIME ~ RIDENAME + TYPE, 
        value.var = "WAITTIMEmean")

dt[dt == "NaN" | dt == "-Inf"] <- NA

print(dt)
```

```{r}
RIDENAME <- c("dwarfs_train", "alien_saucers", "dinosaur", 
               "expedition_everest", "flight_of_passage", "kilimanjaro_safaris", 
               "navi_river", "pirates_of_caribbean", "rock_n_rollercoaster", 
               "slinky_dog", "soarin", "spaceship_earth", "splash_mountain", 
               "toy_story_mania")
open_date <- as.Date(c("2014/05/28", "2018/06/30", "1998/04/22", "2006/04/09", 
                       "2017/05/27", "1998/04/22", "2017/05/27", "1973/12/17", 
                       "1999/07/29", "2018/06/30", "2005/05/15", "1982/10/01", 
                       "1992/07/17", "2008/05/31"))
splash <- c(FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE,  FALSE, FALSE,
            FALSE, FALSE, TRUE,  FALSE)
indoor <- c(FALSE, FALSE, TRUE,  FALSE, TRUE, FALSE, TRUE,  TRUE,  TRUE,  FALSE,
            TRUE,  TRUE,  FALSE, TRUE)
age_hierarchy <- c(10, 13,  4,  8, 11, 5, 12,  1,  6, 14, 7,  2,  3,  9)
park <- c("mk", "hs", "ak", "ak", "ak", "ak", "ak", "mk", "hs", "hs", "ep", 
          "ep", "mk", "hs")
dtMeta <- data.table(RIDENAME, open_date, age_hierarchy, splash, indoor, park)
```

# **I DID A LOG TRANSFORM**

```{r warning=FALSE}
library(GGally)

summary(dt)

sapply(unique(dtMeta$park), function(x) {
  rides <- dtMeta$RIDENAME[dtMeta$park == x]
  cols <- (1:ncol(dt))[grepl(paste0(rides, collapse = "|"), colnames(dt))]
  print(ggpairs(dt[, ..cols], title = paste("Correlation plot for rides in", x), 
                upper = list(continuous = wrap("cor", size = 3)),
                progress = FALSE) +
          theme(text = element_text(size = 6)))
})
```

# **TIME IS IN SECONDS SINCE MIDNIGHT**

```{r, echo = FALSE, results='hide', fig.keep='all'}
library(tree)
library(caret)
library(rpart.plot)

set.seed(1234)
rowPicker <- sample(c(TRUE, FALSE), nrow(dt), replace = TRUE, prob = c(.5, .5))
train <- dt[rowPicker, ]
test <- dt[!rowPicker, ]

sapply(unique(dtMeta$park), function(x) {
  rides <- c(colnames(train)[grepl(paste0(dtMeta$RIDENAME[dtMeta$park == x],
                                        collapse = "|"),
                                 colnames(train))],
             "DATE", "MONTH", "DAY", "TIME")
  actuals <- rides[grepl("(SACTMIN)", rides)]
  return(sapply(actuals, function(y) {
    tr <- rpart(as.formula(paste(y, "~ .")), train[, ..rides])
    rpart.plot(tr, main = y)
    return(tr)
    }))
})
```

